export const colors = {
    light: {
        background: "#FEF8F3",
        surface: "#FFFDFC",
        card: "#FFFFFF",
        text: "#2B1F1D",
        textMuted: "#7B6A67",
        border: "#E7D9D4",
        accent: "#d8725d",
        accentSoft: "#F6D3CB",
        success: "#5FA56B",
        successSoft: "#DDEEDF",
        danger: "#B42318",
        dangerSoft: "#FFF4F4",
        dangerBorder: "#F3C7C7",
        tabInactive: "#9E8B86",
    },
    dark: {
        background: "#1E1518",
        surface: "#2B2125",
        card: "#34282D",
        text: "#F8F1EE",
        textMuted: "#C9B7B2",
        border: "#4A3A40",
        accent: "#F09A86",
        accentSoft: "#5A3A3A",
        success: "#4FA35F",
        successSoft: "#294530",
        danger: "#FFB3C1",
        dangerSoft: "#4A1D25",
        dangerBorder: "#7A2E3A",
        tabInactive: "#B89E98",
    },
    green: {
        background: "#F2F6EF",
        surface: "#FBFDF8",
        card: "#FFFFFF",
        text: "#1F2A21",
        textMuted: "#6F7D70",
        border: "#D8E2D4",
        accent: "#6FA878",
        accentSoft: "#DDEDDC",
        success: "#4F9A5F",
        successSoft: "#DDEEDF",
        danger: "#B42318",
        dangerSoft: "#FFF4F4",
        dangerBorder: "#F3C7C7",
        tabInactive: "#8A9A89",
    },
    yellow: {
        background: "#FFF8E1",
        surface: "#FFFDF2",
        card: "#FFFFFF",
        text: "#2B2516",
        textMuted: "#7A6A45",
        border: "#EADFA8",
        accent: "#D6A300",
        accentSoft: "#FFF0B8",
        success: "#5FA56B",
        successSoft: "#DDEEDF",
        danger: "#B42318",
        dangerSoft: "#FFF4F4",
        dangerBorder: "#F3C7C7",
        tabInactive: "#A39163",
    },
    greenDark: {
        background: "#141D16",
        surface: "#1F2B22",
        card: "#26342A",
        text: "#F3F8F0",
        textMuted: "#B9C9B8",
        border: "#3B4C3E",
        accent: "#8BCB94",
        accentSoft: "#2F4A35",
        success: "#8BCB94",
        successSoft: "#2F4A35",
        danger: "#FFB3C1",
        dangerSoft: "#4A1D25",
        dangerBorder: "#7A2E3A",
        tabInactive: "#9FB29F",
    },

    yellowDark: {
        background: "#1F1A10",
        surface: "#2B2518",
        card: "#352D1D",
        text: "#FFF6DD",
        textMuted: "#D1C39B",
        border: "#4C4127",
        accent: "#F0C94A",
        accentSoft: "#5A4820",
        success: "#8BCB94",
        successSoft: "#2F4A35",
        danger: "#FFB3C1",
        dangerSoft: "#4A1D25",
        dangerBorder: "#7A2E3A",
        tabInactive: "#B8A978",
    },
};

